os: linux

group: stable

service: postgresql

script:

- sudo systemctl start postgresql@13-main

- psql --version

- psql -c 'create database test;' -U postgres

jobs:

  include:

  - dist: focal

    arch: amd64
